export const APP_LIST = {
    "FAKE GPS": {pkgName: "com.blogspot.newapphorizons.fakegps", urlScheme: "", urlParams: ""},
    "GPS Emulator": {pkgName: "com.rosteam.gpsemulator", urlScheme: "", urlParams: ""},
    "FAKE GPS location": {pkgName: "com.lexa.fakegps", urlScheme: "", urlParams: ""},
    "FAKE GPS Location Spoofer": {pkgName: "com.hopefactory2021.fakegpslocation", urlScheme: "", urlParams: ""},
    "Fake GPS Location Profesional": {pkgName: "com.just4funtools.fakegpslocationprofessional", urlScheme: "", urlParams: ""},
    "Location Changer-Fake GPS": {pkgName: "com.locationchanger", urlScheme: "", urlParams: ""},
    "Fake GPS Location - Floater": {pkgName: "com.marlon.floating.fake.location", urlScheme: "", urlParams: ""},
    "Fake Route (Mouck Location)": {pkgName: "app.steve.fakeroute", urlScheme: "", urlParams: ""},
    "Mock GPS with joystick": {pkgName: "net.marlove.mockgps", urlScheme: "", urlParams: ""},
    "Fly GPS-Location/Fake GPS": {pkgName: "com.fly.gps", urlScheme: "", urlParams: ""},
    "Fake GPS Location-GPS Joystick": {pkgName: "com.theappninjas.fakegpsjoystick", urlScheme: "", urlParams: ""},
    "Mock Locations (fake GPS path)": {pkgName: "ru.gavrikov.mocklocations", urlScheme: "", urlParams: ""},
    "Fake GPS Location And Joystick": {pkgName: "com.ninja.toolkit.pulse.fake.gps.pro", urlScheme: "", urlParams: ""},
    "Fake GPS Joystick & Routes Go": {pkgName: "com.incorporateapps.fakegps_route", urlScheme: "", urlParams: ""},
    "Cartage - Fake GPS Locations": {pkgName: "com.mock.cartage", urlScheme: "", urlParams: ""},
    "Life 360: Live Location Sharing": {pkgName: "com.life360.android.safetymapd", urlScheme: "", urlParams: ""},
    "Fake GPS Location-GPS JoyStick": {pkgName: "com.theappninjas.fakegpsjoystick", urlScheme: "", urlParams: ""},
    "FlashGo: cambiar ubicación GPS": { pkgName: "fakegps.fakelocation.mocklocation.gpsfaker", urlScheme: "", urlParams: "" },
    "Ubicación GPS falsa": { pkgName: "fake.gps.location.changer.spoof.location", urlScheme: "", urlParams: "" },
    "Gmocker: GPS Falsa, Fake GPS": { pkgName: "location.changer.fake.gps.spoof.emulator", urlScheme: "", urlParams: "" },
    "GPS falso: ubicación simulada": { pkgName: "top.tinysoft.fakegps", urlScheme: "", urlParams: "" },
    "AnyTo Fake Location - Fake GPS": { pkgName: "com.imyfone.anytoandroid", urlScheme: "", urlParams: "" },
    "Fake GPS Location: подмена GPS": { pkgName: "project.listick.fakegps", urlScheme: "", urlParams: "" },
    "Fake GPS Location Spoofer": { pkgName: "com.incorporateapps.fakegps.fre", urlScheme: "", urlParams: "" },
    "DS Fake GPS Location": { pkgName: "com.discipleskies.mock_location_spoofer", urlScheme: "", urlParams: "" },
    "PGSharp": { pkgName: "com.pgsharp.pokemongo", urlScheme: "", urlParams: "" },
};
